# POLKADOT-PROD values for node-watcher.
# Declare variables to be passed into your templates.

chainName: polkadot
nodeSelector: {}

cloudsql:
  commandline:
    args: "-instances=premiurly-284711:europe-west1:polkassembly=tcp:5432"

nodeWatcher:
  dbName: "polkadot-chain-db"
  dbUser: "chain-db"
  dbPassword: from-gitlab-vars

harvester:
  config:
    ARCHIVE_NODE_ENDPOINT: wss://rpc.polkadot.io
    START_FROM: '0'
