image: parity/kubetools:latest
variables:
  KUBE_NAMESPACE:                  "polkassembly"
  CI_REGISTRY:                     "gcr.io/test-installations-222013"
  DOCKER_TAG:                      $CI_COMMIT_REF_SLUG
  GIT_STRATEGY:                    fetch
  GIT_DEPTH:                       3

stages:
  - test
  - dockerize
  - deploy

cache:
  key:                             '${CI_JOB_NAME}'
  paths:
    - node_modules/
    - packages/*/node_modules/

#### stage:                        test

lint-front-end:
  stage: test
  image: node:12
  interruptible:                   true
  dependencies:                    []
  script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - cd front-end
    - yarn install
    - yarn lint
  rules:
    - changes:
      - "front-end/**/*"
  tags:
    - linux-docker

lint-back-end:
  stage: test
  image: node:12
  interruptible:                   true
  dependencies:                    []
  script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - cd auth-server
    - yarn install
    - yarn lint
  rules:
    - changes:
      - "auth-server/**/*"
  tags:
    - linux-docker

#### stage:                        dockerize

.build_and_push:                   &build_and_push
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
  tags:
    - kubernetes-parity-build
  image: docker:git
  services:
    - docker:dind
  script:
    - POD_NAME=$(echo ${CI_JOB_NAME} | sed -E 's/^[[:alnum:]]+-//')
    - export DOCKER_IMAGE="${CI_REGISTRY}/${KUBE_NAMESPACE}-${POD_NAME}"
    - export DOCKER_IMAGE_FULL_NAME=$DOCKER_IMAGE:$DOCKER_TAG
    - echo "$BUILD_ARGS"
    - echo "$DOCKER_REGISTRY_JSON" | docker login -u _json_key --password-stdin https://gcr.io
    - docker build -t "$DOCKER_IMAGE_FULL_NAME" $(echo -E $BUILD_ARGS) $POD_NAME
    - docker push "$DOCKER_IMAGE_FULL_NAME"

dockerize-front-end:
  stage: dockerize
  environment:
    name: parity-build
  before_script:
    - export BUILD_ARGS="--build-arg REACT_APP_HASURA_GRAPHQL_URL=${REACT_APP_HASURA_GRAPHQL_URL} --build-arg REACT_APP_JWT_PUBLIC_KEY=${REACT_APP_JWT_PUBLIC_KEY}"
  only:
      - master
      - /^fv-.*/
  <<: *build_and_push

dockerize-auth-server:
  stage: dockerize
  environment:
    name: parity-build
  only:
      - master
      - /^fv-.*/
  <<: *build_and_push

#### stage:                        deploy

deploy:
  stage: deploy
  variables:
    http_upgrade: '$http_upgrade' # hack, to make nginx conf work with envsubst
  environment:
    name: dashboards-cluster-1
  tags:
    - kubernetes-parity-build
  only:
    - master
  script:
    # check syntax
    - for f in kubernetes/polkassembly/*yaml; do echo $f; cat $f | envsubst | kubectl --dry-run --validate -n polkassembly apply -f -; done
    # print rendered yaml
    - for f in kubernetes/polkassembly/*yaml; do echo $f; cat $f | envsubst; echo '---'; done
    # deploy yaml to cluster
    - for f in kubernetes/polkassembly/*yaml; do cat $f | envsubst | kubectl -n polkassembly apply -f -; done
