apiVersion: v1
kind: Secret
metadata:
  name: auth-jwt-key
  namespace: polkassembly
type: Opaque
data:
  JWT_PRIVATE_KEY: {{ .Values.authServer.secret.AUTH_SERVER_JWT_PRIVATE_KEY }}
  JWT_PUBLIC_KEY: {{ .Values.authServer.secret.AUTH_SERVER_JWT_PUBLIC_KEY }}
