apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: auth-server
  name: auth-server-config
data:
  BOT_PROPOSAL_USER_ID: "7"
  DATABASE_URL: $DATABASE_URL
  DOMAIN_NAME: polkassembly.io
  DOMAIN_PROTOCOL: http://
  HASURA_POST_SUBSCRIPTION_SECRET: $HASURA_POST_SUBSCRIPTION_SECRET
  JWT_KEY_PASSPHRASE: $JWT_KEY_PASSPHRASE
  JWT_PRIVATE_KEY: $JWT_PRIVATE_KEY
  JWT_PUBLIC_KEY: $JWT_PUBLIC_KEY
  NODE_ENV: development
  PORT: "8010"
  SENDGRID_API_KEY: $SENDGRID_API_KEY
