# Default values for polkassembly.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

chainName: "kusama"
imagePullSecrets: ""
nodeSelector: {}
dockerTag: master

cloudsql:
  commandline:
    args: "-instances=<copy-from-gcp-sql-overview>"
  instanceCredentials: from-gitlab-vars

frontend:
  name: frontend
  replicaCount: 1

  image:
    repository: docker.io/niklabh/polkassembly-kusama-production-front-end
    pullPolicy: Always

  nameOverride: ""
  fullnameOverride: ""

  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    annotations:
    ports:
    - name: http
      port: 80


  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.frontend.entryPoints: "https,http"
    hosts:
      - host: chart-example.local
        path: []
    tls: []

  resources: {}
  tolerations: []
  affinity: {}

hasura:
  name: hasura
  replicaCount: 1

  config:
    HASURA_CHAIN_DB_REMOTE_SCHEMA: "http://chain-db-open-server-service:4000"
    HASURA_GRAPHQL_ADMIN_SECRET: "from-gitlab-vars"
    HASURA_GRAPHQL_DATABASE_URL: "from-gitlab-vars"
    HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup, http-log, webhook-log, websocket-log, query-log"
    HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
    HASURA_POST_SUBSCRIPTION_HOOK: "http://auth-server-service:8010/auth/graphql"
    HASURA_POST_SUBSCRIPTION_SECRET: "from-gitlab-vars"
    HASURA_COMMENT_CREATE_EVENT_HOOK: "http://auth-server-service:8010/auth/event/comment/create"
    HASURA_EVENT_SECRET: "from-gitlab-vars"
    HASURA_AUTH_SERVER_REMOTE_SCHEMA: "http://auth-server-service:8010/auth/graphql"
    HASURA_ONCHAIN_LINK_CREATE_HOOK: "http://auth-server-service:8010/auth/event/onchain_link/create"

  secret:
    HASURA_GRAPHQL_JWT_SECRET: from-gitlab-vars

  image:
    repository: hasura/graphql-engine:v1.3.0-beta.2
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    port: 8080

  resources: {}
  tolerations: []
  affinity: {}

authServer:
  name: auth-server
  replicaCount: 1

  config:
    DOMAIN_NAME: test.polkassembly.io
    NODE_ENV: development
    DOMAIN_PROTOCOL: https://
    PORT: "8010"
    DATABASE_URL: from-gitlab-vars
    HASURA_EVENT_SECRET: from-gitlab-vars
    HASURA_POST_SUBSCRIPTION_SECRET: from-gitlab-vars
    JWT_KEY_PASSPHRASE: from-gitlab-vars
    REDIS_URL: from-gitlab-vars
    SENDGRID_API_KEY: from-gitlab-vars

  secret:
    JWT_PRIVATE_KEY: from-gitlab-vars
    JWT_PUBLIC_KEY: from-gitlab-vars

  image:
    repository: docker.io/niklabh/polkassembly-auth-server
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    port: 8010

  resources: {}
  tolerations: []
  affinity: {}

chainDbWatcher:
  name: chain-db-watcher
  replicaCount: 1

  config:
    PROPOSAL_BOT_USERNAME: "proposal_bot"
    PROPOSAL_BOT_PASSWORD: from-gitlab-vars
    REACT_APP_HASURA_GRAPHQL_URL: "http://hasura-service:8080/v1/graphql"
    AUTH_SERVER_URL: "http://auth-server-service:8010/auth/graphql"
    HASURA_PROPOSAL_POST_TYPE_ID: "2"
    DEMOCRACY_TOPIC_ID: "1"
    COUNCIL_TOPIC_ID: "2"
    TREASURY_TOPIC_ID: "4"
    TECH_COMMITTEE_PROPOSAL_TOPIC_ID: "3"
    START_FROM: "964710"
    HEALTH_PORT: "8019"

  image:
    repository: docker.io/niklabh/polkassembly-chain-db-watcher
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

  podSecurityContext: {}
  securityContext: {}

  resources: {}
  tolerations: []
  affinity: {}

healthMonitor:
  name: health-monitor
  replicaCount: 1

  config:
    # Listening Port
    PORT: 8034
    # polkassembly auth-server
    AUTH_SERVER: "http://auth-server-service:8010"
    # polkassembly hasura graphql service
    HASURA_SERVER: "http://hasura-service:8080"
    # polkassembly hasura chain-db service
    CHAIN_DB_WATCHER_SERVER: "http://chain-db-watcher-service:8019"
    # chain db open server ( CHAIN_DB_SERVER == CHAIN_DB_GRAPHQL_URL )
    CHAIN_DB_SERVER: "http://chain-db-open-server-service:4000"
    # node-watcher server ( aka Prisma server )
    CHAIN_DB: "http://node-watcher-service:4466"
    # polkassembly frontend-service
    REACT_SERVER: "http://frontend-service:80"
    # polkadot rpc node
    ARCHIVE_NODE_ENDPOINT: "wss://kusama-rpc.polkadot.io"

  image:
    repository: docker.io/niklabh/polkassembly-health-monitor
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

  podSecurityContext: {}
  securityContext: {}

  resources: {}
  tolerations: []
  affinity: {}
