# PARITY-PROD values for polkassembly.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

chainName: kusama
nodeSelector: { cloud.google.com/gke-nodepool: apps-pool }

frontend:
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/redirect-entry-point: https
    hosts:
      - host: kusama.polkassembly.io
        path: /
      - host: polkassembly.io
        path: /
    tls: []

authServer:
  config:
    DOMAIN_NAME: "kusama.polkassembly.io"
    PROPOSAL_BOT_USER_ID: "1"

chainDbWatcher:
  config:
    PROPOSAL_BOT_USER_ID: "1"
    CHAIN_DB_GRAPHQL_URL: "http://chain-db-open-server-service:4000"

healthMonitor:
  config:
    # Listening Port
    PORT: 8034
    # polkassembly auth-server
    AUTH_SERVER: "http://auth-server-service:8010"
    # polkassembly hasura graphql service
    HASURA_SERVER: "http://hasura-service:8080"
    # polkassembly hasura chain-db service
    CHAIN_DB_WATCHER_SERVER: "http://chain-db-watcher-service:8019"
    # nomidot backend server ( CHAIN_DB_SERVER == CHAIN_DB_GRAPHQL_URL )
    CHAIN_DB_SERVER: "http://chain-db-open-server-service:4000"
    # nodewatcher server ( aka Prisma server )
    CHAIN_DB: "http://nodedwatcher.nodewatcher-kusama:4466"
    # polkassembly frontend-service
    REACT_SERVER: "http://frontend-service:80"
    # polkadot rpc node
    ARCHIVE_NODE_ENDPOINT: "ws://polkassembly-rpc-internal-0.c.parity-prod.internal:9944"
